-- Create custom types for our enums
CREATE TYPE registration_type AS ENUM ('INDIVIDUAL', 'FAMILY');
CREATE TYPE registration_status AS ENUM ('PENDING', 'PARTIAL_PAID', 'FULLY_PAID', 'CANCELLED');
CREATE TYPE registration_source AS ENUM ('SELF', 'ADMIN');
CREATE TYPE age_category AS ENUM ('ADULT', 'CHILD');

-- 1. Create registrations table
CREATE TABLE registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type registration_type NOT NULL,
  age_category age_category DEFAULT 'ADULT' NOT NULL,
  representative_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  total_fee NUMERIC NOT NULL,
  total_paid NUMERIC DEFAULT 0 NOT NULL,
  status registration_status DEFAULT 'PENDING' NOT NULL,
  registration_source registration_source DEFAULT 'SELF' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Create family_members table
CREATE TABLE family_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_id UUID NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,
  member_name TEXT NOT NULL,
  age_category age_category DEFAULT 'ADULT' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Create payments table
CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  registration_id UUID NOT NULL REFERENCES registrations(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  payment_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  recorded_by UUID REFERENCES auth.users(id), -- Nullable, filled if generated by admin
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Setup Row Level Security (RLS) policies

-- Enable RLS
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE family_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Create policies for registrations
-- 1. Anyone can insert (self-registration)
CREATE POLICY "Anyone can insert registrations" ON registrations
FOR INSERT WITH CHECK (true);

-- 2. Anyone can view their own registration details (assuming we query by phone / ID later)
-- For now, allow public select so users can check status (can be restricted further later)
CREATE POLICY "Anyone can view registrations" ON registrations
FOR SELECT USING (true);

-- 3. Only authenticated users (admins) can update or delete
CREATE POLICY "Admins can update registrations" ON registrations
FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can delete registrations" ON registrations
FOR DELETE USING (auth.role() = 'authenticated');

-- Create policies for family_members
CREATE POLICY "Anyone can insert family_members" ON family_members
FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can view family_members" ON family_members
FOR SELECT USING (true);

CREATE POLICY "Admins can update family_members" ON family_members
FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can delete family_members" ON family_members
FOR DELETE USING (auth.role() = 'authenticated');

-- Create policies for payments
CREATE POLICY "Anyone can view payments" ON payments
FOR SELECT USING (true);

CREATE POLICY "Only admins can insert payments" ON payments
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Only admins can update payments" ON payments
FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Only admins can delete payments" ON payments
FOR DELETE USING (auth.role() = 'authenticated');
